# This file contains additional node's attributes provided by plugin.
# Please, take a look at following link for the details:
# - https://blueprints.launchpad.net/fuel/+spec/nics-and-nodes-attributes-via-plugin
# - https://specs.openstack.org/openstack/fuel-specs/specs/10.0/nics-and-nodes-attributes-via-plugin.html
